openapi: 3.0.1
info:
  title: myapp
  description: My first auto app
  version: 1.0.0
servers:
- url: /api/v1
- url: /graphql
tags:
- name: Examples
  description: Simple example endpoints
- name: Specification
  description: The swagger API specification
paths:
  /examples:
    get:
      tags:
      - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
      - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /examples/{id}:
    get:
      tags:
      - Examples
      parameters:
      - name: id
        in: path
        description: The id of the example to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /things/callback:
    get:
      tags:
      - Callback
      description: Allows the user to login into the thingiverse API
      responses:
        200:
          description: Returns the acces token to the backend in order to be able to work with the thingiverse API
          content: {}
  /things/list/:property:
    get:
      tags:
      - Newest
      description: Allows the user to login into the thingiverse API
      parameters:
      - name: property
        in: path
        description: The id of the thing to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: Returns the acces token to the backend in order to be able to work with the thingiverse API
          content: {}
  /things/things/{id}:
    get:
      tags:
      - Thing
      description: Allows the user to obtain a thing by its id
      parameters:
      - name: id
        in: path
        description: The id of the thing to retrieve
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Return the thing with the specified id
          content: {}
        404:
          description: Resource not found
          content: {}
  /spec:
    get:
      tags:
      - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    ExampleBody:
      title: example
      required:
      - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
